# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
name: Build on PR

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

permissions:
  contents: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    uses: qualcomm-linux/qcom-rpm-utils/.github/workflows/pkg-build-reusable-workflow.yml@main
    with:
      qcom-rpm-utils-ref: main
      cache-base-url: ${{ vars.SRC_TARBALL_CACHE_BASE_URL }}
